blog/urls.py
from django.urls import path
from .views import blog_views, blog_detail_views

app_name = "blog"

urlpatterns = [
    path('', blog_views, name="blog_list"),
    path('<int:id>/', blog_detail_views, name="blog_detail"),
]

conquerblocks/urls.py
from django.contrib import admin
from django.urls import path, include
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("blog/", include('blog.urls', namespace="blog")),
    path("", include('main.urls', namespace="main")),
    path("cursos/", include('cursos.urls', namespace="cursos")),
    path('admin/', admin.site.urls),
] + debug_toolbar_urls() + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cursos/urls.py
from django.urls import path
from .views import cursos_views, cursos_detail_views

app_name = "cursos"

urlpatterns = [
    path('', cursos_views, name="cursos_list"),
    path('<int:id>/', cursos_detail_views, name="cursos_detail"),
]

main/urls.py
from django.urls import path
from .views import about_us_views, contact_views, home_views, login_views, register_views, logout_views, Prueba, PruebaTemplateView, ContactFormView

app_name = "main"

urlpatterns = [
    path('about_us/', about_us_views, name="about_us"),
    path('contact/', contact_views, name="contact"),
    path('contact/ccbv/', ContactFormView.as_view(), name="contact_ccbv"),
    path('', home_views, name="home"),
    path('login/', login_views, name="login"),
    path('logout/', logout_views, name="logout"),
    path('register/', register_views, name="register"),
    path('prueba/', Prueba.as_view(), name="prueba"),
    path('pruebatemplateview/', PruebaTemplateView.as_view(), name="prueba_template_view"),
]

conquerblocks/templates/_includes/_footer.html
<p>Copyright 2025</p>
<p><a href="#">Aviso legal</a></p>

conquerblocks/templates/_includes/_header.html
{% load static %}

<header>
    <a href="">
        <img src="{% static 'img/logotipo_conquer.png' %}" alt="Logo">
    </a>
    {% include '_includes/_main_menu.html' %}
</header>

conquerblocks/templates/_includes/_main_menu.html
<ul>
    <li><a href="{% url 'main:home' %}">Home</a></li>
    <li><a href="{% url 'main:about_us' %}">Quiénes somos</a></li>
    <li><a href="{% url 'cursos:cursos_list' %}">Cursos</a></li>
    <li><a href="{% url 'blog:blog_list' %}">Blog</a></li>
    <li><a href="{% url 'main:register' %}">Registro</a></li>
    <li><a href="{% url 'main:contact' %}">Contacto</a></li>
</ul>

<section class="user">
    {% if request.user.is_authenticated %}
        <p>¡Bienvenido, {{ request.user }}!</p>
        <p><a href="{% url 'main:logout' %}">Cerrar sesión</a></p>
    {% else %}
        <a href="{% url 'main:login' %}">Iniciar sesión</a>
    {% endif %}
</section>