blog/urls.py
from django.urls import path
from .views import blog_views, blog_detail_views

app_name = "blog"

urlpatterns = [
    path('', blog_views, name="blog_list"),
    path('<int:id>/', blog_detail_views, name="blog_detail"),
]

conquerblocks/urls.py
from django.contrib import admin
from django.urls import path, include
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("blog/", include('blog.urls', namespace="blog")),
    path("", include('main.urls', namespace="main")),
    path("cursos/", include('cursos.urls', namespace="cursos")),
    path('admin/', admin.site.urls),
] + debug_toolbar_urls() + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cursos/urls.py
from django.urls import path
from .views import cursos_views, cursos_detail_views

app_name = "cursos"

urlpatterns = [
    path('', cursos_views, name="cursos_list"),
    path('<int:id>/', cursos_detail_views, name="cursos_detail"),
]

main/urls.py
from django.urls import path
from .views import about_us_views, contact_views, home_views, login_views, register_views, logout_views, Prueba, PruebaTemplateView, ContactFormView

app_name = "main"

urlpatterns = [
    path('about_us/', about_us_views, name="about_us"),
    path('contact/', contact_views, name="contact"),
    path('contact/ccbv/', ContactFormView.as_view(), name="contact_ccbv"),
    path('', home_views, name="home"),
    path('login/', login_views, name="login"),
    path('logout/', logout_views, name="logout"),
    path('register/', register_views, name="register"),
    path('prueba/', Prueba.as_view(), name="prueba"),
    path('pruebatemplateview/', PruebaTemplateView.as_view(), name="prueba_template_view"),
]

main/models.py
from django.db import models
from django.utils import timezone

class Contact(models.Model):
    nombre = models.CharField(
        "Nombre",
        max_length = 50
        )
    email = models.EmailField(
        "Email"
    )
    comentario = models.TextField(
        "Comentario que ha dejado en la web"
    )

    created_at = models.DateTimeField(
        "Fecha y hora de creación",
        default=timezone.now
    )

    contacted = models.BooleanField(
        "¿Se ha contactado con esta persona?",
        default=False
    )

    def __str__(self):
        return self.nombre

main/views.py
from django.shortcuts import render

from cursos.models import Curso
from blog.models import Post

from .form import ContactForm, LoginForm, UserRegisterForm
from django.core.mail import send_mail
from .models import Contact

from django.contrib.auth import authenticate, login, logout
from django.shortcuts import redirect

from django.urls import reverse

from django.contrib.auth.models import User

from django.http import HttpResponse
from django.views import View

from django.views.generic.base import TemplateView
from django.views.generic.edit import FormView


def home_views(request):
    context = {
        'posts': Post.objects.filter(show_home=True),
        'cursos': Curso.objects.filter(show_home=True),
    }
    return render(request, 'main/home.html', context)


def about_us_views(request):
    return render(request, 'main/about_us.html')


def login_views(request):
    if request.POST:
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect(reverse('main:home'))
            else:
                context = {
                    'form': form,
                    'error': True,
                    'error_message': 'Usuario no válido'
                }
            return render(request, 'main/login.html', context)  
        else: 
            context = {
                'form': form,
                'error': True
            }     
            return render(request, 'main/login.html', context)  
    else:
        form = LoginForm()
        context = {
            "form": form
        }
        return render(request, 'main/login.html', context)

def logout_views(request):
    logout(request)
    return redirect(reverse('main:home'))

def register_views(request):
    if request.POST:
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            email = form.cleaned_data['email']
            password1 = form.cleaned_data['password1']
            password2 = form.cleaned_data['password2']  

            """Modificado para que se envíe un correo automáticamente:

            message_content = f'{nombre} con email {email} ha escrito lo siguiente: {comentario}'

            Contact.objects.create(
                nombre=nombre,
                email=email,
                comentario=comentario
            )
            success = send_mail(
                "Formulario de contacto de mi web",
                message_content,
                "mendozagonzalez.irene@gmail.com",
                ["iremen19@gmail.com", "mendozagonzalez.irene@gmail.com"],
                fail_silently=False,
            )

            context = {
                "formulario": ContactForm(),  # Resetear el formulario después del éxito
                "success": success,
            }

        """
        
            user = User.objects.create_user(username, email, password1)  
            if user:
                user.first_name = first_name
                user.last_name = last_name
                user.save()

            context = {
                "msj": 'Usuario creado correctamente'
            }

            return render(request, 'main/register.html', context)
        else:
            context = {
                'form': form,
                'error': True
            }  
            return render(request, 'main/register.html', context)
    else:
        form = UserRegisterForm()
        context = {
            "form": form
        }
    return render(request, 'main/register.html', context)


def contact_views(request):
    if request.method == 'POST':
        formulario = ContactForm(request.POST)
        
        if formulario.is_valid():
            nombre = formulario.cleaned_data['nombre']
            email = formulario.cleaned_data['email']
            comentario = formulario.cleaned_data['comentario']
            
            # Aquí deberías enviar el correo real
            print(f'Se ha enviado un correo a {nombre} al correo {email} con el texto {comentario}')
            
            message_content = f'{nombre} con email {email} ha escrito lo siguiente: {comentario}'

            Contact.objects.create(
                nombre=nombre,
                email=email,
                comentario=comentario
            )
            success = send_mail(
                "Formulario de contacto de mi web",
                message_content,
                "mendozagonzalez.irene@gmail.com",
                ["iremen19@gmail.com", "mendozagonzalez.irene@gmail.com"],
                fail_silently=False,
            )

            context = {
                "formulario": ContactForm(),  # Resetear el formulario después del éxito
                "success": success,
            }
            return render(request, 'main/contact.html', context)
    else:
        formulario = ContactForm()
    
    context = {
        "formulario": formulario
    }
    return render(request, 'main/contact.html', context)

class ContactFormView(FormView):
    template_name = "main/contact.html"
    form_class = ContactForm
    success_url = "/"

    def form_valid(self, form):
        nombre = form.cleaned_data['nombre']
        email = form.cleaned_data['email']
        comentario = form.cleaned_data['comentario']
            
        message_content = f'{nombre} con email {email} ha escrito lo siguiente: {comentario}'

        Contact.objects.create(
            nombre=nombre,
            email=email,
            comentario=comentario
        )
        success = send_mail(
            "Formulario de contacto de mi web",
            message_content,
            "mendozagonzalez.irene@gmail.com",
            ["iremen19@gmail.com", "mendozagonzalez.irene@gmail.com"],
            fail_silently=False,
        )

        return super().form_valid(form)
            
class Prueba(View):
    def get(self, request, *args, **kwargs):
        return HttpResponse("Hello, World!") 

class PruebaTemplateView(TemplateView):
    template_name = "PruebaTemplateView.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["titulo"] = 'Este es mi título'
        return context

class PruebaTemplateView2(PruebaTemplateView):
    template_name = "PruebaTemplateView.html"

conquerblocks/templates/main/about_us.html
{% extends 'layout.html' %}

{% block head_title %}About us{% endblock %}
{% block page_title %}Quienes somos{% endblock %}

conquerblocks/templates/main/contact.html
{% extends 'layout.html' %}

{% block head_title %}Contact{% endblock %}
{% block page_title %}Contactanos{% endblock %}

{% block page_content %}
{% if success %}
    <p>Se ha enviado el formulario correctamente</p>
{% else %}
    <form action="" method="POST">
        {% csrf_token %}
        <div>
            {{ form.as_p }}
        </div>
        <button>Enviar</button> 
    </form>
{% endif %}
{% endblock %}

conquerblocks/templates/main/home.html
{% extends 'layout.html' %}
{% load static %}

{% block head_title %}Home{% endblock %}
{% block page_content %}   
    <h1>CONQUER BLOCKS - HOME</h1>
    {% if cursos %}
      <section>
        <h2>Nuestros cursos más aclamados</h2>
        {% for curso in cursos %}
          <div>
            {% if curso.curso_image %}
              <img src="{{ curso.curso_image.thumbnails.small.url }}" alt="Imagen del curso {{ curso.title }}">
            {% endif %}
            <h3>{{ curso.title }}</h3>
            <p>{{ curso.content|truncatewords:100 }}...</p>
            <a href="{% url 'cursos:cursos_detail' curso.pk %}">Ver más</a>
          </div>
        {% endfor %}
      </section>
    {% endif %}
    {% if posts %}
      <section>
        <h2>Últimas noticias</h2>
        {% for post in posts %}
          <h3>{{ post.title }}</h3>
          <p>{{ post.content|truncatewords:40 }}...</p>
          <a href="{% url 'blog:blog_detail' post.pk %}">Ver más</a>
        {% endfor %}
      </section>
    {% endif %}

{% endblock %}

conquerblocks/templates/main/login.html
{% extends 'layout.html' %}

{% block head_title %}Login{% endblock %}


{% block page_content %}

<h1>Login</h1>
{% if error_message %}
    <p>{{error_message}}</p>
{% endif %}
<form action="." method="POST">
    {% csrf_token %}
    <div>
        {{ form.as_p }}
    </div>
    
    <button>Enviar</button>
</form>

{% endblock %}

conquerblocks/templates/main/register.html
{% extends 'layout.html' %}

{% block head_title %}Register{% endblock %}
{% block page_content %}
<h1>¿Aún no tienes una cuenta? ¡A qué estás esperando!</h1>
{% if form %}
    {% if error_message %}
        <p>{{error_message}}</p>
    {% endif %}
    <form action="." method="POST">
        {% csrf_token %}
        <div>
            {{ form.as_p }}
        </div>
    
        <button>Enviar</button>
    </form>
{% else %}
    {{ msj }}
{% endif %}
{% endblock %}